wso2/choreo-samples

oasDefinitions/petstore.yaml
Associated https://github.com/wso2-enterprise/choreo/issues/18765
> Link(s) to product documentation that addresses the changes …
=> Add sample open api definition for api proxy

index.json
=> Update sample thumbnail URLs

.azure/build.yaml
https://github.com/wso2-enterprise/choreo/issues/24589
=> Create a pipeline to upload content to storage account

.azure/build.yaml
https://github.com/wso2-enterprise/choreo/issues/24589
=> Specify overwrite flag

hello-world-mi/readme.md
=> fix typo in mi HelloWorld sample readme

greeting-service-go/README.md, product-management-service/README.md, reading-books-list-service-nodejs/README.md, reading-books-list-service-python/readme.md
=> Update readme file for service

hello-world-nodejs-task/metadata.yaml
=> Fix component name

.azure/process_metadata.py
=> Update index version

scatter-gather-messaging/metadata.yaml
=> Fix long tag name

hello-world-java-task/Procfile
=> Update Procfile For Java Sample

.azure/process_metadata.py, hello-world-php-task/metadata.yaml
- Validate component type and build preset name exactly
- Fix php naming
> Link(s) to product documentation that addresses the …
=> Improve validation logic

.azure/process_metadata.py
- Validate component type and build preset name exactly
- Fix php naming
- Add more component types
> Link(s) to product …
=> Add more component types

.azure/process_metadata.py
- Validate component type and build preset name exactly
- Fix php naming
- Add more component types
- Add postman buildpreset
> …
=> Add postman build preset

.azure/process_metadata.py
=> Bump index version

reading-books-list-service-nodejs/metadata.yaml, reading-books-list-service-python/metadata.yaml
=> Fix issues in samples

customer-reward-management/rewards-frontend/reward-management-api/jwtutil.bal, customer-reward-management/vendor-management/reward-vendor/main.go
> To remove unwanted logs from customer reward management sample
Related issue https://github.com/wso2-enterprise/choreo/issues/25111
> To remove unwanted logs from customer reward management sample
> remove unwanted logs from customer reward management sample
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer …
=> Remove unwanted logs from customer reward management sample

.azure/process_metadata.py, test-runner-javascript/metadata.yaml
=> replace javascript buildpreset from nodejs

.azure/process_metadata.py
> Task - https://github.com/wso2-enterprise/choreo/issues/25078
=> update index.json verion

customer-reward-management/rewards-frontend/reward-management-api/service.bal
> To remove unwanted configs in customer reward mgt
> To remove unwanted configs in customer reward mgt
> Type “Sent” when …
=> Remove unwanted configs in customer reward mgt

product-management-service/.choreo/endpoints.yaml, reading-books-list-service-nodejs/.choreo/endpoints.yaml, reading-books-list-service-python/.choreo/endpoints.yaml
=> Add missing .choreo folder

.azure/build.yaml, .azure/pr-check.yaml, .azure/validate_samples.py
=> PR check test

.azure/pr-check.yaml, .samples/azure-cosmosdb-data-as-rest-api.yaml
=> Test for PR check

.samples/azure-cosmosdb-data-as-rest-api.yaml
=> add faling change to test pr check

.azure/validate_samples.py
=> add catch 

.azure/pr-check.yaml
=> remove comments

.samples/azure-cosmosdb-data-as-rest-api.yaml
=> fix worng component path

.azure/scripts/process_metadata.py, README.md
> Task - https://github.com/wso2-enterprise/choreo/issues/25078
=> add readme instructions on adding new samples

customer-reward-management/rewards-frontend/reward-management-web-app/src/components/Q2Portal/Q2Portal.tsx
to
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
=> Handle undefined values in Account page

.samples/reading-list-app.yaml
> Task - https://github.com/wso2-enterprise/choreo/issues/25078
=> update reading list app metadata

.azure/scripts/process_metadata.py
=> sample index version update

reading-list-app/reading-list-service/service.bal
> To add the changes made to https://github.com/wso2/choreo-examples repo in https://github.com/wso2/choreo-examples/pull/50 since the choreo-examples repo is being deprecated.
=> Adding function to get book by id and adding Location header to POST /books

question-answering-app/question-answering-data-loader/README.md, question-answering-app/question-answering-data-loader/config_loader.py, question-answering-app/question-answering-data-loader/constants.py, question-answering-app/question-answering-data-loader/data/example-data.csv, question-answering-app/question-answering-data-loader/main.py, question-answering-app/question-answering-data-loader/requirements.txt
$title
related issue: https://github.com/wso2-enterprise/choreo/issues/25027
=> Updates to question answering application sample

model-gateway-service/Dependencies.toml, model-gateway-service/service.bal
$title
related issue: https://github.com/wso2-enterprise/choreo/issues/25622
=> Updates to the model gateway sample

reading-list-app/reading-list-front-end-with-managed-auth/src/api/books/constants.ts
$subject to align with the default config template we display in the UI
=> Change window.config to window.configs

.azure/scripts/metadata_validator.py, .azure/scripts/process_metadata.py, .samples/dotnet-greeter.yaml, dotnet-greeter/readme.md, hello-world-python-task/readme.md
https://github.com/wso2-enterprise/choreo/issues/26117 …
=> Update dotnet greeting service

.samples/model-gateway-service.yaml
> To fix https://github.com/wso2-enterprise/choreo/issues/26115
=> add missing dispaly name and description

.azure/scripts/process_metadata.py, .azure/scripts/validate_samples.py
> Improve PR check logic to check mandatory display name and description in meta data.
> Link to the PR for changes to the …
=> improve pr-check logic

.samples/hello-world-php-service.yaml
Partially addresses: https://github.com/wso2-enterprise/choreo/issues/26190
=> Fix description typo in php hello world service sample

.samples/hello-world-dotnet-task.yaml, .samples/hello-world-dotnet-webapp.yaml
https://github.com/wso2-enterprise/choreo/issues/26117 …
=> Add tags as a list

.azure/scripts/process_metadata.py
=> update index version for next release

.azure/scripts/validate_samples.py
> Update PR check logic to check tags is a list
=> check tags is a list PR check

.azure/build.yaml, .azure/scripts/process_metadata.py, .azure/scripts/version_manager.py
=> support for automatic version update

.azure/build.yaml
=> fix yaml indent issue

.azure/build.yaml
=> add resources block to build.yaml

.azure/build.yaml, .azure/scripts/version_manager.py
=> version file fixes

.azure/build.yaml, .azure/scripts/process_metadata.py
=> publish index-v0.json to use as fallback index file

.azure/build.yaml, .azure/scripts/process_metadata.py
=> index resolve from index file

hello-world-ruby-service/.choreo/endpoints.yaml
=> Update endpoints.yaml with schemaFilePath

hello-world-php-task/readme.md
=> Update PHP version

reading-list-app/reading-list-service/Ballerina.toml
=> Bump bal version of reading list svc

pet-care-b2b-app/pet-management-webapp/nx.json, pet-care-b2b-app/pet-management-webapp/package-lock.json, pet-care-b2b-app/pet-management-webapp/package.json
=> Remove cloud runner

.samples/go-grpc.yaml, go-grpc/greeter_client/main.go, go-grpc/greeter_server/main.go, go-grpc/pkg/greeter.proto, go-grpc/readme.md
=> update readme and remove refs to sample-apps

go-grpc/go.mod, go-grpc/greeter_client/main.go, go-grpc/greeter_server/main.go, go-grpc/pkg/greeter.proto
=> fix typos in go grpc service

reading-list-app/reading-list-front-end-with-managed-auth/src/api/books/delete-books.ts, reading-list-app/reading-list-front-end-with-managed-auth/src/api/books/get-books.ts, reading-list-app/reading-list-front-end-with-managed-auth/src/api/books/post-books.ts, reading-list-app/reading-list-front-end-with-managed-auth/src/api/retry.ts
$subject
Related issue: https://github.com/wso2-enterprise/choreo/issues/25858
Related Doc PR: https://github.com/wso2/docs-choreo-dev/pull/1542
=> Update managed auth sample app to work with automatic refresh

.samples/react-single-page-app.yaml, .samples/vue-single-page-application.yaml
This PR fixes some mistakes found in sample metadata
- Fix Name, Description of Vue SPA
- Remove redundant tag in React SPA
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Fix sample metadata mistakes

chat-service-websocket/readme.md
=> refactor readme file

graphql-service/sample.bal
=> Add mutation to the gql sample

greeting-service/service-to-service/Ballerina.toml, greeting-service/service-to-service/README.md, greeting-service/service-to-service/service.bal
=> Add new repo for testing

.samples/proxy-from-gh.yaml
=> Set a proper description for GH-proxy sample

test-runner-go/go.mod, test-runner-go/go.sum
=> Fix trivy failure in Go runner repo

greeting-service-go/Dockerfile, greeting-service-go/go.mod
=> Fix trivy  failure in greeting-service-go repo

docker-rest-user-service/docs/openapi.yaml
> This PR will bump the docker rest user service openapi spec to v3 as api chat only supports openapi v3. Converted using https://editor.swagger.io/
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …
=> Convert openapi spec of docker rest user service to v3

websocket-chat-app/websocket-chat-service-nodejs/readme.md
=> fix readme issues

.azure/scripts/process_metadata.py
> add index.json version to log message in `.azure/scripts/process_metadata.py`
> Link to the PR for changes to the training …
=> Improve metadata processing logs

go-grpc/readme.md
=> Update readme go-grpc

websocket-chat-app/websocket-chat-service-nodejs/ChatRoom.js
=> Add fix to pass a message for sender

.azure/build.yaml, .azure/pr-check.yaml, .azure/scripts/process_metadata.py, .azure/scripts/trivy-scan.sh, .azure/scripts/validate_samples.py, .samples/docker-time-logger-schedule.yaml, docker-time-logger-schedule/Dockerfile, docker-time-logger-schedule/go.mod
>This PR will add trivy scan to docker images of quick deployable samples during pr check
> Link to the PR for changes to the …
=> Add trivy scan to docker images of quick deployable samples

reading-list-app/reading-list-front-end-with-managed-auth/index.html
Fix the issue of trying to pull an incorrect config file (along with the correct config file), resulting an error being printed to console as the incorrect file cannot be json parsed.
=> Fix config reading in Managed auth sample app

.samples/appointment-management.yaml, appointment-management/appointment-service/.choreo/component.yaml, appointment-management/appointment-service/.gitignore, appointment-management/appointment-service/appointmentModel.js, appointment-management/appointment-service/database.js, appointment-management/appointment-service/openapi.yaml, appointment-management/appointment-service/package-lock.json, appointment-management/appointment-service/package.json, appointment-management/appointment-service/readme.md, appointment-management/appointment-service/server.js
This PR will add a sample for db connections usage.
Source: https://github.com/wso2con2024/choreo-tutorial/tree/main/appointment-management/appointment-service
This contains a backed of an appointment service which interacts with a database for CRUD operations.
> Link(s) to product …
=> Add sample for db connections

appointment-management/appointment-service/database.js
=> Update env variable names for db connections sample

.samples/go-graphql-service.yaml
=> Remove go graphql service quick deploy

.azure/scripts/validate_samples.py, docker-rest-user-service/.choreo/endpoints.yaml, go-reading-list-rest-api/.choreo/endpoints.yaml
>$subject
resolves: https://github.com/wso2-enterprise/choreo/issues/32350
> Link to the PR for changes to the training content …
=> Add endpoints.yaml for quick deployable samples

appointment-management/appointment-service/.choreo/component.yaml, appointment-management/readme.md
=> Add modifications to appointment management system

reading-list-app/reading-list-front-end-with-managed-auth/src/index.tsx
=> Fix display logged in user name in Managed Auth App

github-event-to-email-webhook/readme.md, shopify-slack-order-notfication-service/readme.md
=> Update sample readme's to remove stale instructions

.samples/petstore-api-proxy-from-github.yaml, department-api-proxy-from-github/readme.md, petstore-api-proxy-from-github/.choreo/component.yaml, petstore-api-proxy-from-github/openapi.yaml, petstore-api-proxy-from-github/readme.md
$subject
https://github.com/wso2-enterprise/choreo/issues/30924 …
=> Add Petstore github proxy sample

user-management-service/main.go
related to https://github.com/wso2-enterprise/choreo/issues/34452
This pull request includes a change to the `user-management-service/main.go` file to update the path for reading user information from a mounted file.
* [`user-management-service/main.go`](diffhunk://#diff-605562053b4d405379db2be82df452bf42b4ad6bec074b5cfdd008cd6da9a5c5L68-R68): Changed the `dirPath` variable to point to the correct resources directory (`/src/resources/application.yaml`).## Purpose
> Describe how you are implementing the solutions. Include an animated …
=> Change source directory

user-management-service/.choreo/component.yaml
This pull request includes changes to the `user-management-service/.choreo/component.yaml` file to correct property names and ensure consistency in the configuration definitions.
Configuration corrections:
* Corrected the `age` property name to ensure it is properly recognized and displayed as "Age".
* Corrected the `occupation` property name to ensure it is properly recognized and displayed as "Occupation".
> Summary of …
=> Fix issue in defined schema

user-management-service/main.go
This pull request includes a minor change to the `user-management-service/main.go` file. The change ensures that the `user-info` and `index` fields in the JSON response are properly enclosed in double quotes.
* [`user-management-service/main.go`](diffhunk://#diff-605562053b4d405379db2be82df452bf42b4ad6bec074b5cfdd008cd6da9a5c5L80-R81): Modified the `getUserDetails` function to ensure the `user-info` and `index` fields in the JSON response are enclosed in double quotes.
> Describe how you are implementing the solutions. Include an …
=> Fix issue in parsing output json

.azure/scripts/process_metadata.py, .azure/scripts/validate_samples.py
=> Fix issue in validating component path for mcp servers

.azure/scripts/process_metadata.py
=> Skip componentpath check for mcp servers

.azure/scripts/process_metadata.py
=> Validate directories only for non mcp servers

go-reading-list-rest-api/docs/openapi.yaml
Add scopes for Get reading list book by id endpoint  …
=> Add scopes for Get reading list book by id endpoint

.samples/mcp-aws-kb-search-server.yaml, .samples/mcp-brave-search-server.yaml, .samples/mcp-everart-server.yaml, .samples/mcp-github-server.yaml, .samples/mcp-gitlab-server.yaml, .samples/mcp-google-drive-server.yaml, .samples/mcp-google-maps-server.yaml, .samples/mcp-puppeteer-server.yaml, .samples/mcp-redis-server.yaml, .samples/mcp-sentry-server.yaml, .samples/mcp-slack-server.yaml
=> Add package registry as a tag

.azure/scripts/validate_samples.py, .samples/mcp-redis-server.yaml
https://github.com/wso2-enterprise/choreo/issues/35101 …
=> Fix issue in redis server image details

.samples/mcp-aws-kb-search-server.yaml, .samples/mcp-brave-search-server.yaml, .samples/mcp-everart-server.yaml, .samples/mcp-github-server.yaml, .samples/mcp-gitlab-server.yaml, .samples/mcp-google-drive-server.yaml, .samples/mcp-google-maps-server.yaml, .samples/mcp-puppeteer-server.yaml, .samples/mcp-redis-server.yaml, .samples/mcp-sentry-server.yaml, .samples/mcp-slack-server.yaml
=> Update documentation paths of mcp servers

appointment-management/web-portal/frontend/public/index.html, customer-reward-management/rewards-frontend/reward-management-web-app/public/index.html, hotel-reservation-app/hotel-reservation-frontend/public/index.html, reading-list-app/reading-list-front-end-with-managed-auth/index.html, websocket-chat-app/websocket-chat-app-frontend/index.html
This pull request updates the way the `config.js` file is referenced in several frontend applications. The main change is to remove the `public/` directory from the script source path, so that each app now loads `config.js` directly from the root directory. This helps standardize how configuration files are loaded and may help prevent issues with incorrect file paths.
Frontend configuration loading:
* Updated the script reference for `config.js` in `customer-reward-management/rewards-frontend/reward-management-web-app/public/index.html` to remove the `public/` directory from the path.
* Updated the script reference for `config.js` in `reading-list-app/reading-list-front-end-with-managed-auth/index.html` to remove the `public/` directory from the path.
* Updated the script reference for …
=> Update script source paths in HTML files to remove redundant 'public' directory reference
